name: build and verify

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-verify:
    runs-on: ubuntu-latest

    permissions:
      checks: write
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: maven
          server-id: 'github-sxda-scout-addon'
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD

      - name: Build zip with Maven and run tests
        env:
          MAVEN_USERNAME: 'nisrael'
          MAVEN_PASSWORD: ${{ secrets.READ_REGISTRY_TOKEN }}
        run: |
          ./mvnw verify \
            -B --fail-at-end --no-transfer-progress --file pom.xml

      - name: Publish Unit Test Report
        if: success() || failure()
        uses: scacap/action-surefire-report@v1
        with:
          report_paths: '**/surefire-reports/TEST-*.xml, **/failsafe-reports/TEST-*.xml, **/karma-reports/**/test-*.xml'
