name: build and publish image

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

env:
  DOCKER_IMAGE_REGISTRY: ghcr.io/${{ github.repository }}
  DOCKER_REGISTRY_USERNAME: ${{ github.actor }}
  DOCKER_REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}


jobs:
  build-and-publish-image:
    runs-on: ubuntu-latest

    permissions:
      checks: write
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image for main branch
        if: github.ref == 'refs/heads/main'
        run: |
          ./mvnw install \
            -B --no-transfer-progress --file pom.xml \
            -D docker.app.image.registry=${{ env.DOCKER_IMAGE_REGISTRY }} \
            -D docker.app.image.sha=${GITHUB_SHA::7} \
            -P exec.docker.image \
            -am -pl addondemo.app.image

      - name: Format branch name for Docker tag
        if: github.ref != 'refs/heads/main'
        run: |
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          FORMATTED_BRANCH_NAME=${BRANCH_NAME//\//-}
          echo "FORMATTED_BRANCH_NAME=$FORMATTED_BRANCH_NAME" >> $GITHUB_ENV

      - name: Build and push image for all branches except main
        if: github.ref != 'refs/heads/main'
        run: |
          ./mvnw install \
            -B --no-transfer-progress --file pom.xml \
            -D docker.app.image.registry=${{ env.DOCKER_IMAGE_REGISTRY }} \
            -D docker.app.image.tag=${{ env.FORMATTED_BRANCH_NAME }} \
            -D docker.app.image.sha=${GITHUB_SHA::7} \
            -P exec.docker.image \
            -am -pl addondemo.app.image


