name: build and publish image

on:
  workflow_dispatch:
  push:
    branches: [ "**" ]

env:
  DOCKER_IMAGE_REGISTRY: ghcr.io/${{ github.repository }}
  DOCKER_REGISTRY_USERNAME: ${{ github.actor }}
  DOCKER_REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}


jobs:
  build-and-publish-image:
    runs-on: ubuntu-latest

    permissions:
      checks: write
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build and push image except for main branch
        if: github.ref != 'refs/heads/main'
        run: |
          ./mvnw install \
            -B --no-transfer-progress --file pom.xml \
            -D docker.app.image=${{ env.DOCKER_IMAGE_REGISTRY }}:${GITHUB_SHA::7} \
            -D jib.to.auth.username=${{ env.DOCKER_REGISTRY_USERNAME }} \
            -D jib.to.auth.password=${{ env.DOCKER_REGISTRY_PASSWORD }} \
            -D jib.from.auth.username=${{ secrets.DOCKERHUB_USERNAME }} \
            -D jib.from.auth.password=${{ secrets.DOCKERHUB_TOKEN }} \
            -P exec.docker.image \
            -am -pl addondemo.app.image

      - name: Build and push image for main branch
        if: github.ref == 'refs/heads/main'
        run: |
          ./mvnw install \
            -B --no-transfer-progress --file pom.xml \
            -D docker.app.image=${{ env.DOCKER_IMAGE_REGISTRY }}:latest \
            -D jib.to.auth.username=${{ env.DOCKER_REGISTRY_USERNAME }} \
            -D jib.to.auth.password=${{ env.DOCKER_REGISTRY_PASSWORD }} \
            -D jib.from.auth.username=${{ secrets.DOCKERHUB_USERNAME }} \
            -D jib.from.auth.password=${{ secrets.DOCKERHUB_TOKEN }} \
            -P exec.docker.image \
            -am -pl addondemo.app.image
