name: build and publish image

on:
  workflow_dispatch:
  push:
    branches: [ "**" ]

env:
  DOCKER_IMAGE_REGISTRY: ghcr.io/${{ github.repository }}
  DOCKER_REGISTRY_USERNAME: ${{ github.actor }}
  DOCKER_REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}


jobs:
  build-and-publish-image:
    runs-on: ubuntu-latest

    permissions:
      checks: write
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Set DOCKER_APP_IMAGE for all branches except main
        if: github.ref != 'refs/heads/main'
        run: echo "DOCKER_APP_IMAGE=$(echo ${{ env.DOCKER_IMAGE_REGISTRY }}:${GITHUB_SHA::7})" >> $GITHUB_ENV

      - name: Set DOCKER_APP_IMAGE for main branch
        if: github.ref == 'refs/heads/main'
        run: echo "DOCKER_APP_IMAGE=$(echo ${{ env.DOCKER_IMAGE_REGISTRY }}:latest})" >> $GITHUB_ENV

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        run: |
          ./mvnw install \
            -B --no-transfer-progress --file pom.xml \
            -D docker.app.image=${{ env.DOCKER_APP_IMAGE }} \
            -P exec.docker.image \
            -am -pl addondemo.app.image
